import { useState, useEffect } from 'react'

import './Popup.css'
import { generateKeys } from '../utils'

export const Popup = () => {
  const [count, setCount] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  const [publicKey, setPublicKey] = useState('')
  const [privateKey, setPrivateKey] = useState('')

  const add = () => setCount(count + 1)

  useEffect(() => {
    chrome.storage.sync.get(['count'], (result) => {
      setCount(result.count || 0)
    })
  }, [])

  useEffect(() => {
    chrome.storage.sync.set({ count })
    chrome.runtime.sendMessage({ type: 'COUNT', count })
  }, [count])

  useEffect(() => {
    chrome.storage.sync.get(['publicKey', 'privateKey'], (result) => {
      setPublicKey(result.publicKey)
      setPrivateKey(result.privateKey)
    })

    setCount(0)
  }, [])

  const generateTokens = async () => {
    const { publicKey, privateKey } = await generateKeys({
      name: 'name',
      email: 'email@email.com',
    })

    chrome.storage.sync.set({ publicKey: publicKey, privateKey: privateKey })

    window.location.reload()
  }

  return (
    <main>
      <h3>Popup Page</h3>
      <div className="calc">
        <button onClick={() => generateTokens()} disabled={count <= 0}>
          -
        </button>
        <label>{count}</label>
        <button onClick={add}>+</button>
      </div>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
      <div>
        <h3>Public Key</h3>
        <p>{publicKey}</p>
      </div>
      <div>
        <h3>Private Key</h3>
        <p>{privateKey}</p>
      </div>
    </main>
  )
}

export default Popup
